"""add lead_scores table

Revision ID: 030e11901603
Revises: 2e72182da01e
Create Date: 2026-06-22 18:12:26.607702
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '030e11901603'
down_revision: str | None = '2e72182da01e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0.0 AND 1.0', name='ck_lead_scores_confidence_range'),
    sa.CheckConstraint('score BETWEEN 0 AND 100', name='ck_lead_scores_score_range'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_scores_deal', 'lead_scores', ['deal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lead_scores_deal', table_name='lead_scores')
    op.drop_table('lead_scores')
    # ### end Alembic commands ###
