"""add deal_tasks table

Revision ID: 0f45110ee4b3
Revises: d1c1a6781d25
Create Date: 2026-06-22 13:01:13.858499
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0f45110ee4b3'
down_revision: str | None = 'd1c1a6781d25'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_tasks',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_done', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deal_tasks_deal', 'deal_tasks', ['deal_id'], unique=False)
    op.create_index('idx_deal_tasks_owner_deal', 'deal_tasks', ['owner_user_id', 'deal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_deal_tasks_owner_deal', table_name='deal_tasks')
    op.drop_index('idx_deal_tasks_deal', table_name='deal_tasks')
    op.drop_table('deal_tasks')
    # ### end Alembic commands ###
