"""replace deal_tasks with projects and tasks tables

Revision ID: 2e72182da01e
Revises: 35462d0ecda7
Create Date: 2026-06-22 16:36:09.611894
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '2e72182da01e'
down_revision: str | None = '35462d0ecda7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_deal', 'projects', ['deal_id'], unique=False)
    op.create_index('idx_projects_owner', 'projects', ['owner_user_id'], unique=False)
    op.create_index('idx_projects_owner_deal', 'projects', ['owner_user_id', 'deal_id'], unique=False)
    op.create_table('tasks',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_done', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_owner_project', 'tasks', ['owner_user_id', 'project_id'], unique=False)
    op.create_index('idx_tasks_project', 'tasks', ['project_id'], unique=False)
    op.drop_index(op.f('idx_deal_tasks_deal'), table_name='deal_tasks')
    op.drop_index(op.f('idx_deal_tasks_owner_deal'), table_name='deal_tasks')
    op.drop_table('deal_tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_tasks',
    sa.Column('deal_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_done', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('deal_tasks_deal_id_fkey')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('deal_tasks_owner_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deal_tasks_pkey'))
    )
    op.create_index(op.f('idx_deal_tasks_owner_deal'), 'deal_tasks', ['owner_user_id', 'deal_id'], unique=False)
    op.create_index(op.f('idx_deal_tasks_deal'), 'deal_tasks', ['deal_id'], unique=False)
    op.drop_index('idx_tasks_project', table_name='tasks')
    op.drop_index('idx_tasks_owner_project', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_projects_owner_deal', table_name='projects')
    op.drop_index('idx_projects_owner', table_name='projects')
    op.drop_index('idx_projects_deal', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
