"""add freelancer profile fields to users

Revision ID: 35462d0ecda7
Revises: 0f45110ee4b3
Create Date: 2026-06-22 14:05:16.995208
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '35462d0ecda7'
down_revision: str | None = '0f45110ee4b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('professional_title', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('service_categories', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('users', sa.Column('is_listed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_listed')
    op.drop_column('users', 'service_categories')
    op.drop_column('users', 'professional_title')
    # ### end Alembic commands ###
