"""add proof columns to lead_scores

Revision ID: 4012c83d6e60
Revises: 56e20fd0474e
Create Date: 2026-07-16 17:06:08.170171
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4012c83d6e60"
down_revision: str | None = "56e20fd0474e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "lead_scores",
        sa.Column("breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("lead_scores", sa.Column("next_step", sa.Text(), nullable=True))
    op.add_column(
        "lead_scores",
        sa.Column("detected_signals", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("lead_scores", sa.Column("prompt_version", sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lead_scores", "prompt_version")
    op.drop_column("lead_scores", "detected_signals")
    op.drop_column("lead_scores", "next_step")
    op.drop_column("lead_scores", "breakdown")
    # ### end Alembic commands ###
