"""add deal_attachments table

Revision ID: a3430072765c
Revises: d8afe394da6d
Create Date: 2026-07-14 10:37:52.855807
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a3430072765c'
down_revision: str | None = 'd8afe394da6d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_attachments',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deal_attachments_deal', 'deal_attachments', ['deal_id'], unique=False)
    op.create_index('idx_deal_attachments_owner', 'deal_attachments', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_deal_attachments_owner', table_name='deal_attachments')
    op.drop_index('idx_deal_attachments_deal', table_name='deal_attachments')
    op.drop_table('deal_attachments')
    # ### end Alembic commands ###
