"""extend lead_scores with qualification signals and add ai_qualification_confidence to deals

Revision ID: a47770745920
Revises: 030e11901603
Create Date: 2026-06-22 18:18:29.889059
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'a47770745920'
down_revision: str | None = '030e11901603'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('ai_qualification_confidence', sa.Float(), nullable=True))
    op.add_column('lead_scores', sa.Column('project_type', sa.String(length=200), nullable=True))
    op.add_column('lead_scores', sa.Column('budget_signal', sa.String(length=200), nullable=True))
    op.add_column('lead_scores', sa.Column('timeline_signal', sa.String(length=200), nullable=True))
    op.add_column('lead_scores', sa.Column('urgency_signal', sa.String(length=200), nullable=True))
    op.add_column('lead_scores', sa.Column('red_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_scores', 'red_flags')
    op.drop_column('lead_scores', 'urgency_signal')
    op.drop_column('lead_scores', 'timeline_signal')
    op.drop_column('lead_scores', 'budget_signal')
    op.drop_column('lead_scores', 'project_type')
    op.drop_column('deals', 'ai_qualification_confidence')
    # ### end Alembic commands ###
