"""add intake_form_configs and intake_form_fields tables

Revision ID: bb2f7c75ecd9
Revises: a47770745920
Create Date: 2026-06-22 22:25:33.370058
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'bb2f7c75ecd9'
down_revision: str | None = 'a47770745920'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_form_configs',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), server_default='Gửi yêu cầu dự án', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', name='uq_intake_form_configs_owner')
    )
    op.create_index('idx_intake_form_configs_owner', 'intake_form_configs', ['owner_user_id'], unique=False)
    op.create_table('intake_form_fields',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('placeholder', sa.String(length=500), nullable=True),
    sa.Column('field_type', sa.String(length=50), server_default='text', nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['intake_form_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_id', 'field_key', name='uq_intake_form_fields_form_key')
    )
    op.create_index('idx_intake_form_fields_form', 'intake_form_fields', ['form_id', 'sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_intake_form_fields_form', table_name='intake_form_fields')
    op.drop_table('intake_form_fields')
    op.drop_index('idx_intake_form_configs_owner', table_name='intake_form_configs')
    op.drop_table('intake_form_configs')
    # ### end Alembic commands ###
