"""add project_type service_category pricing_tier to deals

Revision ID: d1c1a6781d25
Revises: h3c4d5e6f7a8
Create Date: 2026-06-21 21:42:22.897916
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'd1c1a6781d25'
down_revision: str | None = 'h3c4d5e6f7a8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('project_type', sa.String(length=200), nullable=True))
    op.add_column('deals', sa.Column('service_category', sa.String(length=200), nullable=True))
    op.add_column('deals', sa.Column('pricing_tier', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'pricing_tier')
    op.drop_column('deals', 'service_category')
    op.drop_column('deals', 'project_type')
    # ### end Alembic commands ###
