"""add ai qualification signal fields to deals

Revision ID: dc9c988de307
Revises: bb2f7c75ecd9
Create Date: 2026-06-24 05:17:31.860386
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'dc9c988de307'
down_revision: str | None = 'bb2f7c75ecd9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('ai_qualification_reasoning', sa.Text(), nullable=True))
    op.add_column('deals', sa.Column('ai_qualification_project_type', sa.String(length=200), nullable=True))
    op.add_column('deals', sa.Column('ai_qualification_budget_signal', sa.String(length=200), nullable=True))
    op.add_column('deals', sa.Column('ai_qualification_timeline_signal', sa.String(length=200), nullable=True))
    op.add_column('deals', sa.Column('ai_qualification_urgency_signal', sa.String(length=200), nullable=True))
    op.add_column('deals', sa.Column('ai_qualification_red_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'ai_qualification_red_flags')
    op.drop_column('deals', 'ai_qualification_urgency_signal')
    op.drop_column('deals', 'ai_qualification_timeline_signal')
    op.drop_column('deals', 'ai_qualification_budget_signal')
    op.drop_column('deals', 'ai_qualification_project_type')
    op.drop_column('deals', 'ai_qualification_reasoning')
    # ### end Alembic commands ###
