"""replace_client_tags_with_description

Revision ID: e1e4d3b18786
Revises: 0001
Create Date: 2026-06-11 11:35:51.361728
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'e1e4d3b18786'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_client_tags_client'), table_name='client_tags')
    op.drop_table('client_tags')
    op.alter_column('ai_cost_records', 'input_hash',
               existing_type=sa.CHAR(length=64),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_index(op.f('idx_ai_cost_records_module'), table_name='ai_cost_records')
    op.create_index('idx_ai_cost_records_module', 'ai_cost_records', ['ai_module', 'occurred_at'], unique=False)
    op.drop_index(op.f('idx_ai_cost_records_time'), table_name='ai_cost_records')
    op.create_index('idx_ai_cost_records_time', 'ai_cost_records', ['occurred_at'], unique=False)
    op.drop_index(op.f('idx_ai_cost_records_user'), table_name='ai_cost_records')
    op.create_index('idx_ai_cost_records_user', 'ai_cost_records', ['user_id', 'occurred_at'], unique=False)
    op.drop_index(op.f('idx_audit_log_actor'), table_name='audit_log_entries')
    op.create_index('idx_audit_log_actor', 'audit_log_entries', ['actor_user_id', 'occurred_at'], unique=False)
    op.drop_index(op.f('idx_audit_log_event'), table_name='audit_log_entries')
    op.create_index('idx_audit_log_event', 'audit_log_entries', ['event_type', 'occurred_at'], unique=False)
    op.drop_index(op.f('idx_audit_log_target'), table_name='audit_log_entries')
    op.create_index('idx_audit_log_target', 'audit_log_entries', ['target_type', 'target_id', 'occurred_at'], unique=False)
    op.alter_column('billing_events', 'currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=True)
    op.drop_index(op.f('idx_billing_events_user'), table_name='billing_events')
    op.create_index('idx_billing_events_user', 'billing_events', ['user_id', 'occurred_at'], unique=False)
    op.drop_index(op.f('idx_client_comm_logs_client'), table_name='client_communication_logs')
    op.create_index('idx_client_comm_logs_client', 'client_communication_logs', ['client_id', 'communicated_at'], unique=False)
    op.add_column('clients', sa.Column('description', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_clients_owner_name'), table_name='clients', postgresql_ops={'name': 'text_pattern_ops'})
    op.drop_index(op.f('uq_clients_owner_email'), table_name='clients', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_milestones_invoice'), table_name='contract_payment_milestones', postgresql_where='(invoice_id IS NOT NULL)')
    op.drop_index(op.f('uq_contracts_share_token'), table_name='contracts', postgresql_where='(share_token IS NOT NULL)')
    op.drop_index(op.f('idx_deal_activity_entries_deal'), table_name='deal_activity_entries')
    op.create_index('idx_deal_activity_entries_deal', 'deal_activity_entries', ['deal_id', 'created_at'], unique=False)
    op.alter_column('deals', 'currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'VND'::bpchar"))
    op.drop_index(op.f('idx_deals_owner_created'), table_name='deals')
    op.create_index('idx_deals_owner_created', 'deals', ['owner_user_id', 'created_at'], unique=False)
    op.drop_index(op.f('idx_invoice_payment_records_invoice'), table_name='invoice_payment_records')
    op.create_index('idx_invoice_payment_records_invoice', 'invoice_payment_records', ['invoice_id', 'payment_date'], unique=False)
    op.alter_column('invoices', 'currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'VND'::bpchar"))
    op.drop_index(op.f('idx_invoices_owner_issued'), table_name='invoices')
    op.create_index('idx_invoices_owner_issued', 'invoices', ['owner_user_id', 'issue_date'], unique=False)
    op.drop_index(op.f('idx_pipeline_snapshots_owner'), table_name='pipeline_snapshots')
    op.create_index('idx_pipeline_snapshots_owner', 'pipeline_snapshots', ['owner_user_id', 'snapshot_date'], unique=False)
    op.drop_index(op.f('uq_proposals_share_token'), table_name='proposals', postgresql_where='(share_token IS NOT NULL)')
    op.drop_index(op.f('idx_proposals_owner_created'), table_name='proposals')
    op.create_index('idx_proposals_owner_created', 'proposals', ['owner_user_id', 'created_at'], unique=False)
    op.drop_index(op.f('idx_reminder_delivery_records_reminder'), table_name='reminder_delivery_records')
    op.create_index('idx_reminder_delivery_records_reminder', 'reminder_delivery_records', ['reminder_id', 'attempted_at'], unique=False)
    op.drop_index(op.f('idx_revenue_snapshots_owner'), table_name='revenue_snapshots')
    op.create_index('idx_revenue_snapshots_owner', 'revenue_snapshots', ['owner_user_id', 'period_type', 'period_start'], unique=False)
    op.alter_column('subscription_plans', 'currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::bpchar"))
    op.drop_index(op.f('idx_system_templates_parent'), table_name='system_templates', postgresql_where='(parent_template_id IS NOT NULL)')
    op.alter_column('users', 'currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'VND'::bpchar"))
    op.alter_column('users', 'locale',
               existing_type=sa.CHAR(length=5),
               type_=sa.String(length=5),
               existing_nullable=False,
               existing_server_default=sa.text("'vi'::bpchar"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'locale',
               existing_type=sa.String(length=5),
               type_=sa.CHAR(length=5),
               existing_nullable=False,
               existing_server_default=sa.text("'vi'::bpchar"))
    op.alter_column('users', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'VND'::bpchar"))
    op.create_index(op.f('idx_system_templates_parent'), 'system_templates', ['parent_template_id'], unique=False, postgresql_where='(parent_template_id IS NOT NULL)')
    op.alter_column('subscription_plans', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::bpchar"))
    op.drop_index('idx_revenue_snapshots_owner', table_name='revenue_snapshots')
    op.create_index(op.f('idx_revenue_snapshots_owner'), 'revenue_snapshots', ['owner_user_id', 'period_type', sa.literal_column('period_start DESC')], unique=False)
    op.drop_index('idx_reminder_delivery_records_reminder', table_name='reminder_delivery_records')
    op.create_index(op.f('idx_reminder_delivery_records_reminder'), 'reminder_delivery_records', ['reminder_id', sa.literal_column('attempted_at DESC')], unique=False)
    op.drop_index('idx_proposals_owner_created', table_name='proposals')
    op.create_index(op.f('idx_proposals_owner_created'), 'proposals', ['owner_user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('uq_proposals_share_token'), 'proposals', ['share_token'], unique=True, postgresql_where='(share_token IS NOT NULL)')
    op.drop_index('idx_pipeline_snapshots_owner', table_name='pipeline_snapshots')
    op.create_index(op.f('idx_pipeline_snapshots_owner'), 'pipeline_snapshots', ['owner_user_id', sa.literal_column('snapshot_date DESC')], unique=False)
    op.drop_index('idx_invoices_owner_issued', table_name='invoices')
    op.create_index(op.f('idx_invoices_owner_issued'), 'invoices', ['owner_user_id', sa.literal_column('issue_date DESC')], unique=False)
    op.alter_column('invoices', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'VND'::bpchar"))
    op.drop_index('idx_invoice_payment_records_invoice', table_name='invoice_payment_records')
    op.create_index(op.f('idx_invoice_payment_records_invoice'), 'invoice_payment_records', ['invoice_id', sa.literal_column('payment_date DESC')], unique=False)
    op.drop_index('idx_deals_owner_created', table_name='deals')
    op.create_index(op.f('idx_deals_owner_created'), 'deals', ['owner_user_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('deals', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'VND'::bpchar"))
    op.drop_index('idx_deal_activity_entries_deal', table_name='deal_activity_entries')
    op.create_index(op.f('idx_deal_activity_entries_deal'), 'deal_activity_entries', ['deal_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('uq_contracts_share_token'), 'contracts', ['share_token'], unique=True, postgresql_where='(share_token IS NOT NULL)')
    op.create_index(op.f('idx_milestones_invoice'), 'contract_payment_milestones', ['invoice_id'], unique=False, postgresql_where='(invoice_id IS NOT NULL)')
    op.create_index(op.f('uq_clients_owner_email'), 'clients', ['owner_user_id', 'email'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_clients_owner_name'), 'clients', ['owner_user_id', 'name'], unique=False, postgresql_ops={'name': 'text_pattern_ops'})
    op.drop_column('clients', 'description')
    op.drop_index('idx_client_comm_logs_client', table_name='client_communication_logs')
    op.create_index(op.f('idx_client_comm_logs_client'), 'client_communication_logs', ['client_id', sa.literal_column('communicated_at DESC')], unique=False)
    op.drop_index('idx_billing_events_user', table_name='billing_events')
    op.create_index(op.f('idx_billing_events_user'), 'billing_events', ['user_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.alter_column('billing_events', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=True)
    op.drop_index('idx_audit_log_target', table_name='audit_log_entries')
    op.create_index(op.f('idx_audit_log_target'), 'audit_log_entries', ['target_type', 'target_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.drop_index('idx_audit_log_event', table_name='audit_log_entries')
    op.create_index(op.f('idx_audit_log_event'), 'audit_log_entries', ['event_type', sa.literal_column('occurred_at DESC')], unique=False)
    op.drop_index('idx_audit_log_actor', table_name='audit_log_entries')
    op.create_index(op.f('idx_audit_log_actor'), 'audit_log_entries', ['actor_user_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.drop_index('idx_ai_cost_records_user', table_name='ai_cost_records')
    op.create_index(op.f('idx_ai_cost_records_user'), 'ai_cost_records', ['user_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.drop_index('idx_ai_cost_records_time', table_name='ai_cost_records')
    op.create_index(op.f('idx_ai_cost_records_time'), 'ai_cost_records', [sa.literal_column('occurred_at DESC')], unique=False)
    op.drop_index('idx_ai_cost_records_module', table_name='ai_cost_records')
    op.create_index(op.f('idx_ai_cost_records_module'), 'ai_cost_records', ['ai_module', sa.literal_column('occurred_at DESC')], unique=False)
    op.alter_column('ai_cost_records', 'input_hash',
               existing_type=sa.String(length=64),
               type_=sa.CHAR(length=64),
               existing_nullable=True)
    op.create_table('client_tags',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_client_tags_client')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_tags')),
    sa.UniqueConstraint('client_id', 'tag', name=op.f('uq_client_tags_tag'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_client_tags_client'), 'client_tags', ['client_id'], unique=False)
    # ### end Alembic commands ###
