"""add ai qualification signal fields to deals

Revision ID: e3f359c35eaf
Revises: dc9c988de307
Create Date: 2026-06-24 05:19:15.586808
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'e3f359c35eaf'
down_revision: str | None = 'dc9c988de307'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
