"""add deal_intakes table

Revision ID: e59ec510b7af
Revises: e1e4d3b18786
Create Date: 2026-06-12 12:58:44.993908
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'e59ec510b7af'
down_revision: str | None = 'e1e4d3b18786'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_intakes',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('inquiry_text', sa.Text(), nullable=False),
    sa.Column('estimated_budget', sa.String(length=255), nullable=True),
    sa.Column('desired_timeline', sa.String(length=255), nullable=True),
    sa.Column('source', postgresql.ENUM('inbound', 'referral', 'outreach', 'platform', 'other', name='deal_source', create_type=False), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deal_intakes_client', 'deal_intakes', ['client_id'], unique=False)
    op.create_index('idx_deal_intakes_owner', 'deal_intakes', ['owner_user_id'], unique=False)
    op.create_index('idx_deal_intakes_owner_deleted', 'deal_intakes', ['owner_user_id', 'deleted_at'], unique=False)
    op.create_index('idx_deal_intakes_submitted', 'deal_intakes', ['submitted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_deal_intakes_submitted', table_name='deal_intakes')
    op.drop_index('idx_deal_intakes_owner_deleted', table_name='deal_intakes')
    op.drop_index('idx_deal_intakes_owner', table_name='deal_intakes')
    op.drop_index('idx_deal_intakes_client', table_name='deal_intakes')
    op.drop_table('deal_intakes')
    # ### end Alembic commands ###
